---
- hosts: sw
  gather_facts: no
  connection: local

  tasks:
    - name: configure 3A
      ios_config:
        lines:
          - aaa new-model
          - aaa authentication login noise line none
          - aaa authentication login ise group radius local none
          - aaa authentication dot1x default group radius
          - aaa authorization exec ise group radius login
          - radius-server host 192.168.1.250 key cisco
          - radius-server host 192.168.1.251 key cisco
    - name: configure console
      ios_config:
        lines:
          - login authentication noise
        parents: line console 0
    - name: configure vty
      ios_config:
        lines:
          - exec-timeout 30 0
          - authorization exec ise
          - login authentication ise
          - transport install all
          - end
        parents: line vty 0 15
    - name: svae configure
      ios_config: save_when=modified