---
- hosts: ios
  gather_facts: false
  connection: local

  tasks:
    - name: configure interface
      ios_config:
        lines:
          - description test
          - switchport mode trunk
        parents: interface GigabitEthernet0/1